apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-node-redis
    app.kubernetes.io/name: sample-node-redis
    tags.datadoghq.com/env: alpha
    tags.datadoghq.com/service: sample-node-redis
    tags.datadoghq.com/version: redis
  name: sample-node-redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-node-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-node-redis
        app.kubernetes.io/name: sample-node-redis
        tags.datadoghq.com/env: alpha
        tags.datadoghq.com/service: sample-node-redis
        tags.datadoghq.com/version: redis
        version: redis
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: redis
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 100m
              memory: 120Mi
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
