apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
    tags.datadoghq.com/env: alpha
    tags.datadoghq.com/service: sample-node
    tags.datadoghq.com/version: latest
  name: sample-node
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        tags.datadoghq.com/env: alpha
        tags.datadoghq.com/service: sample-node
        tags.datadoghq.com/version: latest
        version: latest
    spec:
      containers:
        - image: nalbam/sample-node:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-node
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 120Mi
            requests:
              cpu: 100m
              memory: 120Mi
