apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-redis.yaml
  - deployment.yaml
  - service-monitor.yaml
  - service-preview.yaml
  - service-redis.yaml
  - service.yaml
