apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
    release: prometheus-operator
  name: sample-node
spec:
  selector:
    matchLabels:
      app: sample-node
  endpoints:
    - interval: 10s
      path: /metrics
      port: http
