env:
  - name: PROFILE
    value: dev
image:
  repository: nalbam/docs
  tag: v0.0.21
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: docs-dev.bruce.spic.me
      paths:
        - /
  tls:
    - hosts:
        - docs-dev.bruce.spic.me
      secretName: docs-nalbam-tls
service:
  port: 1948
