apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-node-prod
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: sample-node
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-demo-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
