apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-docs-prod
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: apps
    targetRevision: HEAD
    helm:
      valueFiles:
        - sample-docs/base.yaml
        - sample-docs/values-demo-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
