apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-docs-prod
spec:
  project: default
  source:
    repoURL: "https://opspresso.github.io/helm-charts"
    targetRevision: v0.1.5
    helm:
      parameters:
        - name: "image.repository"
          value: "nalbam/docs"
        - name: "image.tag"
          value: "0.2.2"
      values: |
        env:
        - name: PROFILE
          value: prod
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/ssl-redirect: 'true'
          enabled: true
          hosts:
          - host: docs.bruce.spic.me
            paths:
            - /
          tls:
          - hosts:
            - docs.bruce.spic.me
            secretName: sample-docs-tls
        service:
          port: 1948
    chart: sample
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
