apiVersion: v1
data:
  SECRET_MESSAGE: aGVsbG8gcHJvZC1kZW1vIHdvcmxkCg==
  SECRET_VERSION: djAuNC43Mg==
kind: Secret
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
type: Opaque
