apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: sample-spring
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-demo-dev.yaml
    releaseName: sample-spring-dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
