apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-docs-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: apps
    targetRevision: HEAD
    helm:
      valueFiles:
        - sample-docs/values-demo-dev.yaml
    releaseName: sample-docs-dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
