autoscaling:
  enabled: true
  maxReplicas: 4
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 30k
    type: Pods
  minReplicas: 1
configmap:
  data:
    DD_VERSION: v0.4.142
    MESSAGE: hello world
    VERSION: v0.4.142
  enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
  service: sample-spring
  version: v0.4.142
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
fullnameOverride: sample-spring
image:
  repository: nalbam/sample-spring
  tag: v0.4.142
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev.bruce.spic.me
    paths:
    - /
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev-preview.bruce.spic.me
    paths:
    - /
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
revisionHistoryLimit: 1
secret:
  data:
    DARABASE_PASSWORD: cG9zdGdyZXMK
    DARABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vbG9jYWxob3N0OjU0MzIvcG9zdGdyZXMK
    DARABASE_USERNAME: cG9zdGdyZXMK
    SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
    SECRET_VERSION: djAuNC4xNDI=
  enabled: true
service:
  port: 8080
strategy:
  blueGreen:
    activeService: sample-spring
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-spring-preview
