autoscaling:
  enabled: true
  maxReplicas: 4
  metrics:
    - pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 30k
      type: Pods
  minReplicas: 1
configmap:
  data:
    DD_VERSION: v0.4.87
    MESSAGE: hello world
    VERSION: v0.4.87
  enabled: true
datadog:
  enabled: true
  env: alpha
  service: sample-spring
  version: v0.4.87
env:
  - name: PROFILE
    value: dev
image:
  repository: nalbam/sample-spring
  tag: v0.4.87
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-spring.bruce.spic.me
      paths:
        - /
  # tls:
  #   - hosts:
  #       - sample-spring.bruce.spic.me
  #     secretName: sample-spring-tls
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-spring-preview.bruce.spic.me
      paths:
        - /
  # tls:
  #   - hosts:
  #       - sample-spring-preview.bruce.spic.me
  #     secretName: sample-spring-preview-tls
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 10
nameOverride: sample-spring
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 10
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
    SECRET_VERSION: djAuMS4yNA==
  enabled: true
service:
  port: 8080
strategy:
  blueGreen:
    activeService: sample-spring
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-spring-preview
controller:
  kind: Rollout # Deployment or Rollout
