apiVersion: v1
data:
  MESSAGE: hello prod-demo world
  PROFILE: prod
  VERSION: v0.3.11
kind: ConfigMap
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
