apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-webpack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-webpack
        app.kubernetes.io/name: sample-webpack
        version: v0.3.11
    spec:
      containers:
      - env:
        - name: RELOAD_HASH
          value: 8ead08c18a09833fd3cd44bba2c763ad
        - name: CONFIGMAP_HASH
          value: 5a7c9f4bbf82b08f90bb64549e690cfb
        - name: SECRET_HASH
          value: ''
        envFrom:
        - configMapRef:
            name: sample-webpack
        image: nalbam/sample-webpack:v0.3.11
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sample-webpack
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 110m
            memory: 134Mi
          requests:
            cpu: 100m
            memory: 120Mi
