apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs-dev
  namespace: demo-dev
spec:
  project: default
  source:
    repoURL: "https://opspresso.github.io/helm-charts"
    targetRevision: v0.1.5
    helm:
      values: |
        env:
        - name: PROFILE
          value: dev
        image:
          repository: nalbam/docs
          tag: 0.2.2
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/ssl-redirect: 'true'
          enabled: true
          hosts:
          - host: docs-dev.bruce.spic.me
            paths:
            - /
          tls:
          - hosts:
            - docs-dev.bruce.spic.me
            secretName: sample-docs-tls
        service:
          port: 1948
    chart: sample
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-node-dev
  namespace: demo-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: sample-node
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-demo-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-dev
  namespace: demo-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: sample-spring
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-demo-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-tomcat-dev
  namespace: demo-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/opspresso/argocd-env-demo"
    path: sample-tomcat
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-demo-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
