apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
    tags.datadoghq.com/env: alpha
    tags.datadoghq.com/service: sample-node
    tags.datadoghq.com/version: 0.5.2
  name: sample-node
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-node
  strategy:
    canary:
      canaryService: sample-node-preview
      steps:
        - setWeight: 25
        - analysis:
            args:
              - name: url
                value: http://sample-node-preview:3000/success/98
            templateName: http-benchmark
        - setWeight: 50
        - pause:
            duration: 10
        - setWeight: 75
        - pause:
            duration: 10
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        tags.datadoghq.com/env: alpha
        tags.datadoghq.com/service: sample-node
        tags.datadoghq.com/version: 0.5.2
        version: 0.5.2
    spec:
      containers:
        - image: nalbam/sample-node:0.5.2
          imagePullPolicy: Always
          name: sample-node
          resources:
            limits:
              cpu: 110m
              memory: 134Mi
            requests:
              cpu: 110m
              memory: 134Mi
