apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node-preview
spec:
  rules:
    - host: sample-node-preview.bruce.spic.me
      http:
        paths:
          - backend:
              serviceName: sample-node
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - sample-node-preview.bruce.spic.me
      secretName: sample-node-preview-tls
