env:
  - name: PROFILE
    value: prod
  - name: ENV_HASH
    value: f7d9bc25e9cdafca2e867022705e2879
image:
  repository: nalbam/docs
  tag: 0.2.7
ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: >
      "arn:aws:acm:ap-northeast-2:082867736673:certificate/0d73b89e-fcb1-40d0-b157-bc072ef585b8"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: docs.bruce.spic.me
    kubernetes.io/ingress.class: alb
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: docs.bruce.spic.me
      paths:
        - /
  # tls:
  #   - hosts:
  #       - docs.bruce.spic.me
  #     secretName: sample-docs-tls
