env:
  - name: PROFILE
    value: dev
  - name: ENV_HASH
    value: hash_string
image:
  repository: nalbam/docs
  tag: 0.2.5
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: docs-dev.bruce.spic.me
      paths:
        - /
  tls:
    - hosts:
        - docs-dev.bruce.spic.me
      secretName: sample-docs-tls
