env:
  - name: PROFILE
    value: dev
  - name: ENV_HASH
    value: 3ddce04ede7c1768411af1a87b59a8f9
image:
  repository: nalbam/docs
  tag: 0.2.7
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    # kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: docs-dev.bruce.spic.me
      paths:
        - /
  tls:
    - hosts:
        - docs-dev.bruce.spic.me
      secretName: sample-docs-tls
