env:
  - name: PROFILE
    value: prod
  - name: ENV_HASH
    value: f7d9bc25e9cdafca2e867022705e2879
image:
  repository: nalbam/docs
  tag: 0.2.7
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: docs.bruce.spic.me
      paths:
        - /
  tls:
    - hosts:
        - docs.bruce.spic.me
      secretName: sample-docs-tls
