apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: sample-tomcat
  # targetCPUUtilizationPercentage: 80
  metrics:
    - type: Pods
      pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 200k
