apiVersion: v1
data:
  SECRET_MESSAGE: aGVsbG8gcHJvZC1kZW1vIHdvcmxkCg==
  SECRET_VERSION: djAuNC40OQ==
kind: Secret
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
type: Opaque
