apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-tomcat-preview
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat-preview
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-tomcat
    version: v0.4.14-39
