namespace: "demo-prod"

profile: "prod"

replicaCount: 1

image:
  repository: nalbam/docs
  pullPolicy: IfNotPresent
  tag: v0.0.21

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: docs.karrot.spic.me
      paths:
        - /
  tls:
    - hosts:
        - docs.karrot.spic.me
      secretName: docs-nalbam-tls
