apiVersion: v1
data:
  SECRET_MESSAGE: aGVsbG8gZGV2LWRlbW8gd29ybGQK
  SECRET_VERSION: djAuNC42Mg==
kind: Secret
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
type: Opaque
