apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
    release: prometheus-operator
  name: sample-tomcat
spec:
  selector:
    matchLabels:
      app: sample-tomcat
  endpoints:
    - interval: 15s
      port: tcp-jmx
