autoscaling:
  enabled: true
  maxReplicas: 4
  metrics:
    - pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 100k
      type: Pods
  minReplicas: 2
# configmap:
#   data:
#     DD_VERSION: 0.5.2
#     MESSAGE: hello world
#     VERSION: 0.5.2
#   enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
  service: sample-node
  version: 0.5.2
dnsPolicy: Default
env:
  - name: PROFILE
    value: dev
  - name: DD_AGENT_ENABLED
    value: "true"
fullnameOverride: sample-node
hostNetwork: true
image:
  repository: nalbam/sample-node
  tag: 0.5.2
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node-dev.bruce.spic.me
      paths:
        - /
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
podAnnotations:
  chaos.alpha.kubernetes.io/enabled: "true"
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node-dev-preview.bruce.spic.me
      paths:
        - /
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
revisionHistoryLimit: 1
# secret:
#   data:
#     SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
#     SECRET_VERSION: MC41LjYw
#   enabled: true
service:
  port: 3000
strategy:
  blueGreen:
    activeService: sample-node
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-node-preview
sidekicks:
  - name: sample-node-redis
    replicaCount: 1
    revisionHistoryLimit: 5
    image:
      repository: redis
      tag: latest
    service:
      name: redis
      port: 6379
    livenessProbe: {}
    readinessProbe: {}
    resources: {}
    env: []
    envFrom: []
    nodeSelector: {}
    affinity: {}
    tolerations: {}
