apiVersion: v1
data:
  DD_VERSION: 0.5.1
  MESSAGE: hello dev-demo world
  PROFILE: dev
  VERSION: 0.5.1
kind: ConfigMap
metadata:
  labels:
    app: sample-web
    app.kubernetes.io/name: sample-web
  name: sample-web
