livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
podAnnotations:
  chaos.alpha.kubernetes.io/enabled: "true"
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
revisionHistoryLimit: 1
service:
  port: 3000
sidekicks:
  - affinity: {}
    env: []
    envFrom: []
    image:
      repository: redis
      tag: latest
    livenessProbe: {}
    name: sample-node-redis
    nodeSelector: {}
    readinessProbe: {}
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    revisionHistoryLimit: 5
    service:
      name: redis
      port: 6379
    tolerations: []
