autoscaling:
  enabled: true
  maxReplicas: 4
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 10k
    type: Pods
  minReplicas: 2
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
  version: 0.5.12
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: e1bd243bd16fc3a91ce6e420f7b6d223
image:
  repository: nalbam/sample-node
  tag: 0.5.12
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-node-dev.bruce.spic.me
    paths:
    - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-node-dev-preview.bruce.spic.me
    paths:
    - /
strategy:
  blueGreen:
    activeService: sample-node
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-node-preview
