autoscaling:
  enabled: true
  maxReplicas: 8
  metrics:
    - pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 10k
      type: Pods
  minReplicas: 4
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
  - name: PROFILE
    value: prod
  - name: DD_AGENT_ENABLED
    value: "true"
image:
  repository: nalbam/sample-node
  tag: 0.5.10
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node.bruce.spic.me
      paths:
        - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node-preview.bruce.spic.me
      paths:
        - /
strategy:
  canary:
    canaryService: sample-node-preview
    steps:
      - setWeight: 25
      - analysis:
          args:
            - name: url
              value: http://sample-node-preview:3000/success/98
          templateName: http-benchmark
      - setWeight: 50
      - pause:
          duration: 10
      - setWeight: 75
      - pause:
          duration: 10
