autoscaling:
  enabled: true
  maxReplicas: 4
  metrics:
    - pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 10k
      type: Pods
  minReplicas: 2
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
  - name: PROFILE
    value: dev
  - name: DD_AGENT_ENABLED
    value: "true"
  - name: ENV_HASH
    value: 85d9d2b9097bb6edc36d7e7b6fbb5e3e
image:
  repository: nalbam/sample-node
  tag: 0.5.15
ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: >
      "arn:aws:acm:ap-northeast-2:082867736673:certificate/0d73b89e-fcb1-40d0-b157-bc072ef585b8"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: sample-node-dev.bruce.spic.me
    kubernetes.io/ingress.class: alb
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node-dev.bruce.spic.me
      paths:
        - /
preview:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: >
      "arn:aws:acm:ap-northeast-2:082867736673:certificate/0d73b89e-fcb1-40d0-b157-bc072ef585b8"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: sample-node-dev-preview.bruce.spic.me
    kubernetes.io/ingress.class: alb
    kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
    - host: sample-node-dev-preview.bruce.spic.me
      paths:
        - /
strategy:
  blueGreen:
    activeService: sample-node
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-node-preview
