autoscaling:
  enabled: false
  maxReplicas: 4
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 10k
    type: Pods
  minReplicas: 1
configmap:
  data:
    MESSAGE: hello world
    VERSION: 0.5.688
  enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: 1c778a8343f7a38a7abed928d6a15d5e
image:
  repository: nalbam/sample-tomcat
  tag: 0.5.688
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-tomcat-dev.bruce.spic.me
    paths:
    - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-tomcat-dev-preview.bruce.spic.me
    paths:
    - /
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
    SECRET_VERSION: MC41LjY4OA==
  enabled: true
strategy:
  blueGreen:
    activeService: sample-tomcat
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-tomcat-preview
