apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - behavior: merge
    envs:
      - configmap.conf
    name: sample-node
secretGenerator:
  - behavior: merge
    envs:
      - secret.conf
    name: sample-node
    type: Opaque

patchesStrategicMerge:
  - deployment.yaml

resources:
  - ../base
  # - configmap.yaml
  - hpa.yaml
  - ingress-preview.yaml
  - ingress.yaml
  # - secret.yaml
