apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
    tags.datadoghq.com/version: 0.5.1
  name: sample-webpack
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-webpack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-webpack
        app.kubernetes.io/name: sample-webpack
        tags.datadoghq.com/version: 0.5.1
        version: 0.5.1
    spec:
      containers:
      - env:
        - name: RELOAD_HASH
          value: 8ead08c18a09833fd3cd44bba2c763ad
        - name: CONFIGMAP_HASH
          value: 332fa9645e0200fb73efcebfb5d2c535
        - name: SECRET_HASH
          value: 75ee582b67ed96839730736747bb8742
        envFrom:
        - configMapRef:
            name: sample-webpack
        - secretRef:
            name: sample-webpack
        image: nalbam/sample-webpack:0.5.1
        imagePullPolicy: Always
        name: sample-webpack
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 110m
            memory: 134Mi
          requests:
            cpu: 100m
            memory: 120Mi
