autoscaling:
  enabled: false
  maxReplicas: 4
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 10k
    type: Pods
  minReplicas: 1
configmap:
  data:
    MESSAGE: hello world
    VERSION: 0.5.133
  enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: a2a7d2405b6b1b0ce7997ee02d19677f
image:
  repository: nalbam/sample-spring
  tag: 0.5.133
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev.bruce.spic.me
    paths:
    - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev-preview.bruce.spic.me
    paths:
    - /
secret:
  data:
    DARABASE_ADDRESS: ZGItZGVtby5jdjJ3eDZtenp3YncuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20K
    DARABASE_PASSWORD: cG9zdGdyZXMK
    DARABASE_USERNAME: YW9ycS15YXNzSUdpODkK
    SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
    SECRET_VERSION: MC41LjEzMw==
  enabled: true
strategy:
  blueGreen:
    activeService: sample-spring
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-spring-preview
