autoscaling:
  enabled: false
  maxReplicas: 4
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 10k
    type: Pods
  minReplicas: 1
configmap:
  data:
    DATABASE_ADDRESS: db-demo.cv2wx6mzzwbw.ap-northeast-2.rds.amazonaws.com
    DATABASE_USERNAME: postgres
    MESSAGE: hello world
    VERSION: 0.5.1297
  enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: be86b648961a2f4e4e89a8df2a24915b
image:
  repository: nalbam/sample-spring
  tag: 0.5.1297
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev.bruce.spic.me
    paths:
    - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev-preview.bruce.spic.me
    paths:
    - /
secret:
  data:
    DATABASE_PASSWORD: YW9ycS15YXNzSUdpODkK
    SECRET_MESSAGE: c2VjcmV0IHdvcmxkCg==
    SECRET_VERSION: MC41LjEyOTc=
  enabled: true
strategy:
  blueGreen:
    activeService: sample-spring
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-spring-preview
