apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-tomcat-dev
spec:
  project: default
  source:
    repoURL: "https://opspresso.github.io/helm-charts"
    targetRevision: v0.1.5
    helm:
      valueFiles:
        - sample-tomcat-dev.yaml
    chart: sample
    releaseName: sample-tomcat-dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
