apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-web
    app.kubernetes.io/name: sample-web
  name: sample-web
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sample-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-web
        app.kubernetes.io/name: sample-web
        version: v0.4.3
    spec:
      containers:
        - env:
            - name: RELOAD_HASH
              value: 8ead08c18a09833fd3cd44bba2c763ad
            - name: CONFIGMAP_HASH
              value: 9e46ff3949fa45ec5671cff5c803216d
            - name: SECRET_HASH
              value: ""
          envFrom:
            - configMapRef:
                name: sample-web
          image: nalbam/sample-web:v0.4.3
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-web
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 110m
              memory: 134Mi
            requests:
              cpu: 100m
              memory: 120Mi
